/*
 * Copyright 2021 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.process.dmn.pay.garbage.springboot;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GarbageFee implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.math.BigDecimal amount;

    private FeePeriod period;

    public GarbageFee() {
    }

    public java.math.BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(java.math.BigDecimal amount) {
        this.amount = amount;
    }

    public FeePeriod getPeriod() {
        return period;
    }

    public void setPeriod(FeePeriod period) {
        this.period = period;
    }

    public GarbageFee(java.math.BigDecimal amount, FeePeriod period) {
        this.amount = amount;
        this.period = period;
    }

}