package org.kie.kogito.legacy;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Hello implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("Greeting")
    private java.lang.String greeting;

    @org.kie.api.definition.type.Label(value = "Approved")
    private java.lang.Boolean approved;

    public Hello() {
    }

    public java.lang.String getGreeting() {
        return this.greeting;
    }

    public void setGreeting(java.lang.String greeting) {
        this.greeting = greeting;
    }

    public java.lang.Boolean getApproved() {
        return this.approved;
    }

    public void setApproved(java.lang.Boolean approved) {
        this.approved = approved;
    }

    public Hello(java.lang.String greeting, java.lang.Boolean approved) {
        this.greeting = greeting;
        this.approved = approved;
    }

}