{
 "title": "LoanEligibility endpoint metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "LoanEligibility endpoint request count per day",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"LoanEligibility\"}[1d]))"
    }
   ]
  },
  {
   "title": "Average requests per minute to LoanEligibility endpoint",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"LoanEligibility\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint LoanEligibility",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "api_execution_elapsed_nanosecond{endpoint=\"LoanEligibility\"}"
    }
   ]
  },
  {
   "title": "LoanEligibility endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_http_response_code{endpoint=\"LoanEligibility\"}[1m])"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(api_http_stacktrace_exceptions{endpoint=\"LoanEligibility\"}[1d])"
    }
   ]
  },
  {
   "title": "Exception count per day",
   "type": "stat",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions{endpoint=\"LoanEligibility\"}[1d]))"
    }
   ]
  },
  {
   "title": "Decision Eligibility",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(string_dmn_result{endpoint = \"LoanEligibility\", decision = \"Eligibility\"}[10m])"
    }
   ]
  },
  {
   "title": "Decision Judgement",
   "type": "graph",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(string_dmn_result{endpoint = \"LoanEligibility\", decision = \"Judgement\"}[10m])"
    }
   ]
  },
  {
   "title": "Decision Is Enought?",
   "type": "graph",
   "gridPos": { "x": 0, "y": 32, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "number_dmn_result{endpoint = \"LoanEligibility\", decision = \"Is Enought?\"}"
    }
   ]
  },
  {
   "title": "Decision Decide",
   "type": "graph",
   "gridPos": { "x": 12, "y": 32, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(boolean_dmn_result{endpoint = \"LoanEligibility\", decision = \"Decide\"}[10m])"
    }
   ]
  }
 ]
}