{
 "title": "fraud-scoring endpoint metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "fraud-scoring endpoint request count per day",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"fraud-scoring\"}[1d]))"
    }
   ]
  },
  {
   "title": "Average requests per minute to fraud-scoring endpoint",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"fraud-scoring\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint fraud-scoring",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "api_execution_elapsed_nanosecond{endpoint=\"fraud-scoring\"}"
    }
   ]
  },
  {
   "title": "fraud-scoring endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_http_response_code{endpoint=\"fraud-scoring\"}[1m])"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(api_http_stacktrace_exceptions{endpoint=\"fraud-scoring\"}[1d])"
    }
   ]
  },
  {
   "title": "Exception count per day",
   "type": "stat",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions{endpoint=\"fraud-scoring\"}[1d]))"
    }
   ]
  },
  {
   "title": "Decision Total Amount from Last 24 hours Transactions",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "number_dmn_result{endpoint = \"fraud-scoring\", decision = \"Total Amount from Last 24 hours Transactions\"}"
    }
   ]
  }
 ]
}