{
 "title": "TrafficViolation endpoint metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "TrafficViolation endpoint request count per day",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"TrafficViolation\"}[1d]))"
    }
   ]
  },
  {
   "title": "Average requests per minute to TrafficViolation endpoint",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"TrafficViolation\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint TrafficViolation",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "api_execution_elapsed_nanosecond{endpoint=\"TrafficViolation\"}"
    }
   ]
  },
  {
   "title": "TrafficViolation endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_http_response_code{endpoint=\"TrafficViolation\"}[1m])"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(api_http_stacktrace_exceptions{endpoint=\"TrafficViolation\"}[1d])"
    }
   ]
  },
  {
   "title": "Exception count per day",
   "type": "stat",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions{endpoint=\"TrafficViolation\"}[1d]))"
    }
   ]
  },
  {
   "title": "Decision Should the driver be suspended?",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(string_dmn_result{endpoint = \"TrafficViolation\", decision = \"Should the driver be suspended?\"}[10m])"
    }
   ]
  }
 ]
}