package org.kie.kogito.legacy;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Message() {
    }

}