{
 "title": "KogitoTravel Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total travel requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kogito_process_instance_started_total{process_id='travels'})"
    }
   ]
  },
  {
   "title": "Open travel requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kogito_process_instance_running_total{process_id='travels'})"
    }
   ]
  },
  {
   "title": "Canceled travel requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kogito_process_instance_completed_total{status=\"3\", process_id='travels'})"
    }
   ]
  },
  {
   "title": "Completed travel requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kogito_process_instance_completed_total{status=\"2\", process_id='travels'})"
    }
   ]
  },
  {
   "title": "Services invoked",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kogito_work_item_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Visas approved",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "acme_travels_visas_approved_total"
    }
   ]
  },
  {
   "title": "Rule execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(drl_match_fired_nanosecond_sum[1m])",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Rules applied",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "drl_match_fired_nanosecond_count"
    }
   ]
  },
  {
   "title": "Visas rejected",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "acme_travels_visas_rejected_total"
    }
   ]
  },
  {
   "title": "Travel request processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kogito_process_instance_duration_seconds_sum[1m])/avg_over_time(kogito_process_instance_duration_seconds_count[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  }
 ]
}