package com.acme;
unit AlertingService;

import org.kie.kogito.rules.*;

declare Event
   type:  String
   value: int
end

declare Alert
  severity: String
  message:  String
end

rule IncomingEvent when
   // matches when a temperature higher than 30 °C is registered (OOPath syntax)
   $e : /eventData [ type == "temperature", value >= 30 ] 
then
   System.out.println("incoming event: "+ $e.getMessage());
   alertData.append( new Alert( "warning", $e ) );
end

