package org.kie.kogito.serverless

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.node.ObjectNode
import java.lang.Integer

rule "Approve Application"
ruleflow-group "newapplicant"
no-loop
    when
        $w : JsonNode()
        eval( Integer.parseInt($w.get("salary").asText()) > 3000)
    then
        ( (ObjectNode) $w ).put("decision", "Approved");
end

rule "Deny Application"
ruleflow-group "newapplicant"
no-loop
    when
        $w : JsonNode()
        eval( Integer.parseInt($w.get("salary").asText()) < 3000)
    then
        ( (ObjectNode) $w ).put("decision", "Denied");
end

