// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeting.proto

package org.kie.kogito.examples.sw.greeting;

public final class Greeting {
    private Greeting() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface HelloRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:HelloRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         * 
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <code>string name = 1;</code>
         * 
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
                getNameBytes();

        /**
         * <code>string language = 2;</code>
         * 
         * @return The language.
         */
        java.lang.String getLanguage();

        /**
         * <code>string language = 2;</code>
         * 
         * @return The bytes for language.
         */
        com.google.protobuf.ByteString
                getLanguageBytes();
    }

    /**
     * <pre>
     * The request message containing the user's name.
     * </pre>
     *
     * Protobuf type {@code HelloRequest}
     */
    public static final class HelloRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:HelloRequest)
            HelloRequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use HelloRequest.newBuilder() to construct.
        private HelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private HelloRequest() {
            name_ = "";
            language_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new HelloRequest();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
                getUnknownFields() {
            return this.unknownFields;
        }

        private HelloRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            language_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest.class, org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;

        /**
         * <code>string name = 1;</code>
         * 
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         * 
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
                getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LANGUAGE_FIELD_NUMBER = 2;
        private volatile java.lang.Object language_;

        /**
         * <code>string language = 2;</code>
         * 
         * @return The language.
         */
        @java.lang.Override
        public java.lang.String getLanguage() {
            java.lang.Object ref = language_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                language_ = s;
                return s;
            }
        }

        /**
         * <code>string language = 2;</code>
         * 
         * @return The bytes for language.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
                getLanguageBytes() {
            java.lang.Object ref = language_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                language_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, language_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, language_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest)) {
                return super.equals(obj);
            }
            org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest other = (org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest) obj;

            if (!getName()
                    .equals(other.getName()))
                return false;
            if (!getLanguage()
                    .equals(other.getLanguage()))
                return false;
            if (!unknownFields.equals(other.unknownFields))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
            hash = (53 * hash) + getLanguage().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder()
                    : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * The request message containing the user's name.
         * </pre>
         *
         * Protobuf type {@code HelloRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:HelloRequest)
                org.kie.kogito.examples.sw.greeting.Greeting.HelloRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloRequest_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest.class, org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest.Builder.class);
            }

            // Construct using org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                name_ = "";

                language_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloRequest_descriptor;
            }

            @java.lang.Override
            public org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest getDefaultInstanceForType() {
                return org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest.getDefaultInstance();
            }

            @java.lang.Override
            public org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest build() {
                org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest buildPartial() {
                org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest result = new org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest(this);
                result.name_ = name_;
                result.language_ = language_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest) {
                    return mergeFrom((org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest other) {
                if (other == org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest.getDefaultInstance())
                    return this;
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getLanguage().isEmpty()) {
                    language_ = other.language_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <code>string name = 1;</code>
             * 
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             * 
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
                    getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             * 
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             * 
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object language_ = "";

            /**
             * <code>string language = 2;</code>
             * 
             * @return The language.
             */
            public java.lang.String getLanguage() {
                java.lang.Object ref = language_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    language_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string language = 2;</code>
             * 
             * @return The bytes for language.
             */
            public com.google.protobuf.ByteString
                    getLanguageBytes() {
                java.lang.Object ref = language_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    language_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string language = 2;</code>
             * 
             * @param value The language to set.
             * @return This builder for chaining.
             */
            public Builder setLanguage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                language_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string language = 2;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearLanguage() {

                language_ = getDefaultInstance().getLanguage();
                onChanged();
                return this;
            }

            /**
             * <code>string language = 2;</code>
             * 
             * @param value The bytes for language to set.
             * @return This builder for chaining.
             */
            public Builder setLanguageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                language_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:HelloRequest)
        }

        // @@protoc_insertion_point(class_scope:HelloRequest)
        private static final org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest();
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<HelloRequest> PARSER = new com.google.protobuf.AbstractParser<HelloRequest>() {
            @java.lang.Override
            public HelloRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HelloRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<HelloRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<HelloRequest> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.kie.kogito.examples.sw.greeting.Greeting.HelloRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface HelloReplyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:HelloReply)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string message = 1;</code>
         * 
         * @return The message.
         */
        java.lang.String getMessage();

        /**
         * <code>string message = 1;</code>
         * 
         * @return The bytes for message.
         */
        com.google.protobuf.ByteString
                getMessageBytes();
    }

    /**
     * <pre>
     * The response message containing the greetings
     * </pre>
     *
     * Protobuf type {@code HelloReply}
     */
    public static final class HelloReply extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:HelloReply)
            HelloReplyOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use HelloReply.newBuilder() to construct.
        private HelloReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private HelloReply() {
            message_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new HelloReply();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
                getUnknownFields() {
            return this.unknownFields;
        }

        private HelloReply(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            message_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloReply_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloReply_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.kie.kogito.examples.sw.greeting.Greeting.HelloReply.class, org.kie.kogito.examples.sw.greeting.Greeting.HelloReply.Builder.class);
        }

        public static final int MESSAGE_FIELD_NUMBER = 1;
        private volatile java.lang.Object message_;

        /**
         * <code>string message = 1;</code>
         * 
         * @return The message.
         */
        @java.lang.Override
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>string message = 1;</code>
         * 
         * @return The bytes for message.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
                getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof org.kie.kogito.examples.sw.greeting.Greeting.HelloReply)) {
                return super.equals(obj);
            }
            org.kie.kogito.examples.sw.greeting.Greeting.HelloReply other = (org.kie.kogito.examples.sw.greeting.Greeting.HelloReply) obj;

            if (!getMessage()
                    .equals(other.getMessage()))
                return false;
            if (!unknownFields.equals(other.unknownFields))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(org.kie.kogito.examples.sw.greeting.Greeting.HelloReply prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder()
                    : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * The response message containing the greetings
         * </pre>
         *
         * Protobuf type {@code HelloReply}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:HelloReply)
                org.kie.kogito.examples.sw.greeting.Greeting.HelloReplyOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloReply_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloReply_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.kie.kogito.examples.sw.greeting.Greeting.HelloReply.class, org.kie.kogito.examples.sw.greeting.Greeting.HelloReply.Builder.class);
            }

            // Construct using org.kie.kogito.examples.sw.greeting.Greeting.HelloReply.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                message_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return org.kie.kogito.examples.sw.greeting.Greeting.internal_static_HelloReply_descriptor;
            }

            @java.lang.Override
            public org.kie.kogito.examples.sw.greeting.Greeting.HelloReply getDefaultInstanceForType() {
                return org.kie.kogito.examples.sw.greeting.Greeting.HelloReply.getDefaultInstance();
            }

            @java.lang.Override
            public org.kie.kogito.examples.sw.greeting.Greeting.HelloReply build() {
                org.kie.kogito.examples.sw.greeting.Greeting.HelloReply result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public org.kie.kogito.examples.sw.greeting.Greeting.HelloReply buildPartial() {
                org.kie.kogito.examples.sw.greeting.Greeting.HelloReply result = new org.kie.kogito.examples.sw.greeting.Greeting.HelloReply(this);
                result.message_ = message_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.kie.kogito.examples.sw.greeting.Greeting.HelloReply) {
                    return mergeFrom((org.kie.kogito.examples.sw.greeting.Greeting.HelloReply) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.kie.kogito.examples.sw.greeting.Greeting.HelloReply other) {
                if (other == org.kie.kogito.examples.sw.greeting.Greeting.HelloReply.getDefaultInstance())
                    return this;
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.kie.kogito.examples.sw.greeting.Greeting.HelloReply parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.kie.kogito.examples.sw.greeting.Greeting.HelloReply) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object message_ = "";

            /**
             * <code>string message = 1;</code>
             * 
             * @return The message.
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string message = 1;</code>
             * 
             * @return The bytes for message.
             */
            public com.google.protobuf.ByteString
                    getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string message = 1;</code>
             * 
             * @param value The message to set.
             * @return This builder for chaining.
             */
            public Builder setMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 1;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearMessage() {

                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            /**
             * <code>string message = 1;</code>
             * 
             * @param value The bytes for message to set.
             * @return This builder for chaining.
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                message_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:HelloReply)
        }

        // @@protoc_insertion_point(class_scope:HelloReply)
        private static final org.kie.kogito.examples.sw.greeting.Greeting.HelloReply DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new org.kie.kogito.examples.sw.greeting.Greeting.HelloReply();
        }

        public static org.kie.kogito.examples.sw.greeting.Greeting.HelloReply getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<HelloReply> PARSER = new com.google.protobuf.AbstractParser<HelloReply>() {
            @java.lang.Override
            public HelloReply parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HelloReply(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<HelloReply> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<HelloReply> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public org.kie.kogito.examples.sw.greeting.Greeting.HelloReply getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_HelloRequest_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_HelloRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_HelloReply_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_HelloReply_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016greeting.proto\".\n\014HelloRequest\022\014\n\004name" +
                        "\030\001 \001(\t\022\020\n\010language\030\002 \001(\t\"\035\n\nHelloReply\022\017" +
                        "\n\007message\030\001 \001(\t23\n\007Greeter\022(\n\010SayHello\022\r" +
                        ".HelloRequest\032\013.HelloReply\"\000B%\n#org.kie." +
                        "kogito.examples.sw.greetingb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_HelloRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_HelloRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HelloRequest_descriptor,
                new java.lang.String[] { "Name", "Language", });
        internal_static_HelloReply_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_HelloReply_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HelloReply_descriptor,
                new java.lang.String[] { "Message", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
