#!/bin/bash

CALLBACK_STATE_TIMEOUTS_WF=callbackstatetimeouts
EVENT_STATE_TIMEOUTS_WF=eventstatetimeouts
SWITCH_STATE_TIMEOUTS_WF=switchstatetimeouts
WORKFLOW_TIMEOUTS_WF=workflowtimeouts

CALLBACK_STATE_TIMEOUTS_ROOT=`minikube service $CALLBACK_STATE_TIMEOUTS_WF -n timeouts-showcase  --url`
EVENT_STATE_TIMEOUTS_ROOT=`minikube service $EVENT_STATE_TIMEOUTS_WF -n timeouts-showcase  --url`
SWITCH_STATE_TIMEOUTS_ROOT=`minikube service $SWITCH_STATE_TIMEOUTS_WF -n timeouts-showcase  --url`
WORKFLOW_TIMEOUTS_ROOT=`minikube service $WORKFLOW_TIMEOUTS_WF -n timeouts-showcase  --url`

CALLBACK_STATE_TIMEOUTS_URL="$CALLBACK_STATE_TIMEOUTS_ROOT/$CALLBACK_STATE_TIMEOUTS_WF"
EVENT_STATE_TIMEOUTS_URL="$EVENT_STATE_TIMEOUTS_ROOT/$EVENT_STATE_TIMEOUTS_WF"
SWITCH_STATE_TIMEOUTS_URL="$SWITCH_STATE_TIMEOUTS_ROOT/$SWITCH_STATE_TIMEOUTS_WF"
WORKFLOW_TIMEOUTS_URL="$WORKFLOW_TIMEOUTS_ROOT/$WORKFLOW_TIMEOUTS_WF"


echo "Setting workflows env variables to:"
echo "CALLBACK_STATE_TIMEOUTS_URL=$CALLBACK_STATE_TIMEOUTS_URL"
echo "EVENT_STATE_TIMEOUTS_URL=$EVENT_STATE_TIMEOUTS_URL"
echo "SWITCH_STATE_TIMEOUTS_URL=$SWITCH_STATE_TIMEOUTS_URL"
echo "WORKFLOW_TIMEOUTS_URL=$WORKFLOW_TIMEOUTS_URL"
