package org.drools.simple.candrink;
unit People;

import org.kie.kogito.quickstart.Person
import org.kie.kogito.quickstart.Result

rule R1 when
        $r1 : /results
        $p : /persons[ age >= 18 ]
    then
        $r1.setValue( $p.getName() + " can drink");
end

rule R2 when
        $r : /results
        $p : /persons[ age < 18 ]
    then
        $r.setValue( $p.getName() + " can NOT drink");
end

