package org.submarine.hr


rule "Employee exists" 

when
    $emp : Employee()
    $val : EmployeeValidationModel($emp.personalId == employee.personalId)
then
    modify($val) { 
    	setStatus( "exists" ),
    	setMessage( "Employee " + $val.getEmployee().getFirstName() + " " + $val.getEmployee().getLastName() + " is already registered" );
    };
    delete($emp);
end

rule "Employee does not exist" 

when
	$emp : Employee()
    not EmployeeValidationModel($emp.personalId == employee.personalId)
then
    EmployeeValidationModel val = new EmployeeValidationModel();
    val.setEmployee($emp);
    val.setStatus( "new" );
	val.setMessage( "Employee " + $emp.getFirstName() + " " + $emp.getLastName() + " is not yet registered" );
    delete($emp);
    insert(val);
end
