/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.acme.travels

import org.acme.travels.VisaApplication;
import org.acme.travels.VisaResolution;

rule "Visit Australia with e-visa up to 90 days" ruleflow-group "visa-approvals"

when
    $application: VisaApplication(duration <= 90, country == "Australia")
then
    VisaResolution $resolution = new VisaResolution(true, "Visit Australia with e-visa up to 90 days violated"); 
end

rule "Visit US with e-visa up to 15 days" ruleflow-group "visa-approvals"

when
    $application: VisaApplication(duration <= 15, country == "US")
then
    VisaResolution $resolution = new VisaResolution(true, "Visit US with e-visa up to 15 days violated");
end

rule "Default rejection" ruleflow-group "visa-approvals"

when
then
    VisaResolution $resolution = new VisaResolution(false, "Automatic approval not fulfilled"); 
end