/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.acme.travels

import org.acme.travels.VisaApplication;
import org.acme.travels.VisaResolution;

rule "Visit Australia with e-visa up to 90 days" ruleflow-group "visa-approvals"

when
    $application: VisaApplication(duration <= 90, country == "Australia")
    $resolution : VisaResolution()
then
    $resolution.setApproved(true);
    $resolution.setReason("Automatic visa approval");
end

rule "Visit US with e-visa up to 15 days" ruleflow-group "visa-approvals"

when
    $application: VisaApplication(duration <= 15, country == "US")
    $resolution : VisaResolution()
then
    $resolution.setApproved(true);
    $resolution.setReason("Automatic visa approval");
end