package org.kie.kogito.examples.hr
unit Department;

query department
    d: /employee
end

rule "US Employee" when
    $e: /employee/address[country == "US"] 
then
    modify(e) { setDepartment( "US12345" ) };
end

rule "UK Employee" when
    $e: /employee/address[country == "UK"] 
then
    modify(d) { setDepartment( "UK9876" ) };
end

rule "US Department" when
    $d: /employee[ department == "US12345" ]
then
    $d.setManager( "John Doe" );
end

rule "UK Department" when
    $d: /employee[ department == "UK9876" ]
then
    $d.setManager( "Teresa April" );
end

