package org.kie.kogito.examples.hr;
unit EmployeeValidation;

query employeeValidation 
  v:/validation
end

rule "Employee exists" 
when
    emp : /employee and
    val : /validation[ this.getEmployee().getPersonalId() == emp.personalId ]
then
    val.setStatus( "exists" );
    val.setMessage( "Employee " + val.getEmployee().getFirstName() + " " + val.getEmployee().getLastName() + " is already registered" );
end

rule "Employee does not exist" 

when
	emp : /employee and
    not /validation[ this.getEmployee().getPersonalId() == emp.personalId ]
then
    EmployeeValidationModel val = new EmployeeValidationModel();
    val.setEmployee(emp);
    val.setStatus( "new" );
	val.setMessage( "Employee " + emp.getFirstName() + " " + emp.getLastName() + " is not yet registered" );
end
