package org.kie.kogito.examples.hr;
unit EmployeeValidation;

query employeeValidation 
  v:/validation
end

rule "Employee exists" 
when
    emp : /employee[ EmployeeRepository.get().isRegistered(personalId) ] 
then
    EmployeeValidationModel val = new EmployeeValidationModel();
    val.setStatus( "exists" );
    val.setMessage( "Employee " + val.getEmployee().getFirstName() + " " + val.getEmployee().getLastName() + " is already registered" );
    validation.set(val);
end

rule "Employee does not exist" 

when
    emp : /employee[ EmployeeRepository.get().isNotRegistered(personalId) ]
then
    EmployeeValidationModel val = new EmployeeValidationModel();
    val.setEmployee(emp);
    val.setStatus( "new" );
	val.setMessage( "Employee " + emp.getFirstName() + " " + emp.getLastName() + " is not yet registered" );
    validation.set(val);
end
