package org.kie.kogito.examples.hr
unit Id;

import org.kie.kogito.rules.DataSource
import org.kie.kogito.rules.SingletonStore
import org.kie.kogito.rules.RuleUnitData

declare Id extends RuleUnitData 
    employeeData: SingletonStore<IdModel> = DataSource.createSingleton()
end

// query id
//     /employeeData
// end

rule "Assign Employee ID"
when
    $id: /employeeData
then
    $id.setEmployeeId( String.valueOf(($id.getEmployee().getFirstName() + $id.getEmployee().getLastName()).hashCode()));
end

rule "Assign Employee email" 
when
    $id: /employeeData
then
    $id.setEmail( $id.getEmployee().getFirstName() + "." + $id.getEmployee().getLastName() + "@company.com") ;
end
