{
 "title": "dmn-drools-springboot-metrics_${project.version} - Custom - Domain Dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Decision Eligibility",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (identifier) (increase(string_dmn_result_total{endpoint=\"LoanEligibility\",decision=\"Eligibility\",artifactId=\"dmn-drools-springboot-metrics\",version=\"${project.version}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Decision Judgement",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (identifier) (increase(string_dmn_result_total{endpoint=\"LoanEligibility\",decision=\"Judgement\",artifactId=\"dmn-drools-springboot-metrics\",version=\"${project.version}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Decision Is Enough?",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "(sum(increase(number_dmn_result_sum{endpoint=\"LoanEligibility\",decision=\"Is Enough?\",artifactId=\"dmn-drools-springboot-metrics\",version=\"${project.version}\"}[1m])))/(sum(increase(number_dmn_result_count{endpoint=\"LoanEligibility\",decision=\"Is Enough?\",artifactId=\"dmn-drools-springboot-metrics\",version=\"${project.version}\"}[1m])))"
    }
   ]
  },
  {
   "title": "Decision Decide",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (identifier) (increase(boolean_dmn_result_total{endpoint=\"LoanEligibility\",decision=\"Decide\",artifactId=\"dmn-drools-springboot-metrics\",version=\"${project.version}\"}[1m]))"
    }
   ]
  }
 ]
}