/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.kogito.examples;
unit ApplicantValidationUnit;

import org.kie.kogito.examples.LoanApplication;

rule NotAdult
lock-on-active true
when
    $l: /loanApplications[ applicant.age < 20 ]
then
    Applicant $a = $l.getApplicant();
    $a.setInvalid(true);
    modify($l) { setApplicant($a) };
end

rule BadCreditScore 
lock-on-active true
when
    $l: /loanApplications[ applicant.creditScore < 100 ]
then
    Applicant $a = $l.getApplicant();
    $a.setInvalid(true);
    modify($l) { setApplicant($a) };
end

query FindInvalidApplicant
    /loanApplications[ $applicant: applicant, applicant.invalid ]
end

