/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.kogito.examples;
unit CommonUnit;

import org.kie.kogito.examples.LoanApplication;

// ----------------------
// common format check
// ----------------------

rule formatCheckName
salience 1000
when
    $l: /loanApplications[ applicant.name == null || applicant.name == "" ]
then
    modify($l) { setApproved(false) };
end

// more...

// ----------------------
// common code conversion
// ----------------------

rule occupationCategoryA1
when
    $l: /loanApplications[ applicant.occupationCategory == null, applicant.occupationCode == "1021" ]
then
    Applicant $a = $l.getApplicant();
    $a.setOccupationCategory("A");
    modify($l) { setApplicant($a) };
end

rule occupationCategoryA2
when
    $l: /loanApplications[ applicant.occupationCategory == null, applicant.occupationCode == "2099" ]
then
    System.out.println("*** occupationCategoryA2");
    Applicant $a = $l.getApplicant();
    $a.setOccupationCategory("A");
    modify($l) { setApplicant($a) };
end

rule occupationCategoryB
when
    $l: /loanApplications[ applicant.occupationCategory == null, applicant.occupationCode == "1025" ]
then
    Applicant $a = $l.getApplicant();
    $a.setOccupationCategory("B");
    modify($l) { setApplicant($a) };
end

// more....
