{
 "title": "LoanEligibility - Domain Dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Decision Eligibility",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(string_dmn_result{endpoint = \"LoanEligibility\", decision = \"Eligibility\"}[10m])"
    }
   ]
  },
  {
   "title": "Decision Judgement",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(string_dmn_result{endpoint = \"LoanEligibility\", decision = \"Judgement\"}[10m])"
    }
   ]
  },
  {
   "title": "Decision Is Enought?",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "number_dmn_result{endpoint = \"LoanEligibility\", decision = \"Is Enought?\"}"
    }
   ]
  },
  {
   "title": "Decision Decide",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(boolean_dmn_result{endpoint = \"LoanEligibility\", decision = \"Decide\"}[10m])"
    }
   ]
  }
 ]
}