{
 "title": "hello - Operational Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "hello endpoint request count per day",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"hello\"}[1d]))"
    }
   ]
  },
  {
   "title": "Average requests per minute to hello endpoint",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"hello\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint hello",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "api_execution_elapsed_nanosecond{endpoint=\"hello\"}"
    }
   ]
  },
  {
   "title": "hello endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_http_response_code{endpoint=\"hello\"}[1m])"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(api_http_stacktrace_exceptions{endpoint=\"hello\"}[1d])"
    }
   ]
  },
  {
   "title": "Exception count per day",
   "type": "stat",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions{endpoint=\"hello\"}[1d]))"
    }
   ]
  }
 ]
}