{
 "title": "Onboarding Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Started Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_process_instance_started_total)"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_process_instance_running_total)"
    }
   ]
  },
  {
   "title": "Aborted Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_process_instance_completed_total{status=\"3\"})"
    }
   ]
  },
  {
   "title": "Completed Processes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_process_instance_completed_total{status=\"2\"})"
    }
   ]
  },
  {
   "title": "Total rules executed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(drl_match_fired_nanosecond_count)"
    }
   ]
  },
  {
   "title": "Started Process Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kie_process_instance_started_total[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  },
  {
   "title": "Process Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_process_instance_duration_seconds_sum[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  },
  {
   "title": "Work Items Executions",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "kie_work_item_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Rule Fire Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(drl_match_fired_nanosecond_sum[1m])",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Work Item Average Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_work_item_duration_seconds_sum[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rules Executions",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "drl_match_fired_nanosecond_count"
    }
   ]
  }
 ]
}