{
 "title": "bikes endpoint metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "bikes endpoint request count per day",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{handler=\"bikes\"}[1d]))"
    }
   ]
  },
  {
   "title": "Average requests per minute to bikes endpoint",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{handler=\"bikes\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint bikes",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "api_execution_elapsed_nanosecond{handler=\"bikes\"}"
    }
   ]
  },
  {
   "title": "bikes endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_http_response_code{handler=\"bikes\"}[1m])"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(api_http_stacktrace_exceptions{handler=\"bikes\"}[1d])"
    }
   ]
  },
  {
   "title": "Global system exception count per day",
   "type": "stat",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions{handler=\"bikes\"}[1d]))"
    }
   ]
  },
  {
   "title": "Decision Person license",
   "type": "graph",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(string_dmn_result{handler = \"Person license\"}[10m])"
    }
   ]
  },
  {
   "title": "Decision Bike license",
   "type": "graph",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "number_dmn_result{handler = \"Bike license\"}"
    }
   ]
  },
  {
   "title": "Decision Can ride?",
   "type": "graph",
   "gridPos": { "x": 0, "y": 32, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(boolean_dmn_result{handler = \"Can ride?\"}[10m])"
    }
   ]
  }
 ]
}