{
 "title": "world endpoint metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "world endpoint request count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "api_http_requests_total{handler=\"world\"}"
    }
   ]
  },
  {
   "title": "world endpoint status code responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_http_response_code{handler=\"world\"}"
    }
   ]
  },
  {
   "title": "Execution time endpoint",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(api_execution_elapsed_nanosecond_bucket{handler=\"world\"}[1m])) by (le)"
    }
   ]
  },
  {
   "title": "Global system exception count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(api_http_stacktrace_exceptions)"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "api_http_stacktrace_exceptions" }
   ]
  }
 ]
}