{
 "title": "Overall system metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Free memory available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "system_memory_usage{handler=\"freeMemory\"}"
    }
   ]
  },
  {
   "title": "Total memory of the system",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "system_memory_usage{handler=\"totalMemory\"}"
    }
   ]
  },
  {
   "title": "Number of available processors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "system_available_processors{handler=\"totalProcessors\"}"
    }
   ]
  }
 ]
}